from enum import StrEnum


class NTTitle(StrEnum):
    S = "S"
    ClassVarDecList = "ClassVarDecList"
    SubroutineDecList = "SubroutineDecList"
    ClassVarDec = "ClassVarDec"
    Type = "Type"
    VarNameList = "VarNameList"
    VarName = "VarName"
    ClassName = "ClassName"
    SubroutineDec = "SubroutineDec"
    SubroutineName = "SubroutineName"
    ParameterList = "ParameterList"
    TypedVarNameList = "TypedVarNameList"
    SubroutineBody = "SubroutineBody"
    VarDeclarationList = "VarDeclarationList"
    VarDeclaration = "VarDeclaration"
    StatementsList = "StatementsList"
    Statement = "Statement"
    LetStatement = "LetStatement"
    IfStatement = "IfStatement"
    IfHeader = "IfHeader"
    ElsePart = "ElsePart"
    WhileHeader = "WhileHeader"
    WhileStatement = "WhileStatement"
    DoStatement = "DoStatement"
    ReturnStatement = "ReturnStatement"
    Expression = "Expression"
    UnaryOperationList = "UnaryOperationList"
    Term = "Term"
    SubroutineCall = "SubroutineCall"
    ExpressionList = "ExpressionList"
    KeywordConstant = "KeywordConstant"
    UnaryOperation = "UnaryOperation"
    Operation = "Operation"
    ReturnType = "ReturnType"
